### PR TITLE
Enable forms to submit on return

### LINKED ISSUE #390: Submit forms on keyboard enter event

### PR DESCRIPTION
**Pull request by valentinewallace**
Closes  #390

### CODE REVIEW

**Comment by tanx** [comment]
Tested this but it crashed the app:
image

**Comment by tanx** [comment]
In storybook it seems to work. But not if a text input if focused.

**Comment by tanx** [comment]
Also, I added autoFocus to all text inputs where appropriate.
Closes #415

**Comment by valentinewallace** [comment]
tested out the build, works well for me! merging

**Pull request merged**
