### PR TITLE
Update documentation for mobile development

### PR DESCRIPTION
**Pull request by otech47**
Some extra guidance was needed to explain how
the React Native mobile app is built and tested.

I described the problems I had following the existing
README to try to build the app in an Android simulator
using GenyMotion on Mac OSX. Therefore, the issues
may be machine-specific and there may be a better place
for some of these details, but for now I figured a
Known Issues would be straightforward enough

Also I made some assumptions on how the development
environment mocks the application state so there
may be a configuration I'm not aware of that
simulates mainnet or testnet conditions

Some of this may help with or be related to
lightninglabs/lightning-app#1223

### CODE REVIEW

**Comment by tanx** [comment]
Hey @otech47, thanks so much. But we're currently migrating away from expo and I just today created new docs for mobile:

https://github.com/lightninglabs/lightning-app/pull/1240/commits/a1e3713adb0da404e9aa2b5711b7f6a37a7fa111#diff-1f94ecec14ddad9cd153c79b5db1dfbc

**Comment by tanx** [comment]
Closing in favor of the new bare builds. @otech47 sorry but let me know if you are able to build the app using the instructions in the README and if anything is missing.

**Comment by otech47** [comment]
@tanx all good I figured there would be something coming soon given all the workaround-ing to do in that development environment but no worries! I'll check out the new docs later this week and try to do a fresh build to see if I run into any issues that can help improve the docs.

**Comment by otech47** [comment]
@tanx Took a bit of time to try and get up and running but couldn't quite follow the docs as is. Have some ideas for improvements but first I'm having problems with building the mobile binaries.

I am able through the _Running the App_ section no problem and get an iOS sim up and running but then I get a 

```
'Lndmobile/Lndmobile.h' file not found
```

which is of course because of missing lnd mobile binaries. Then I went back through the _Building lnd/Building_ section and hit this issue

Screen Shot 2019-07-31 at 8 43 24 PM

I am imagining this is related to the **lnd mobile build tools** mentioned in the dependencies but the link (https://github.com/lightninglabs/lnd/tree/mobile-autopilot-100) doesn't seem to be found on GitHub so that's where I'm stuck. Could you point me in the right direction of getting the mobile build tools and I can try to keep working through this? 

Let me know if you'd rather move this convo somewhere else or if this thread is fine for now.

**Comment by tanx** [comment]
Yes. You'll need to use @halseth's branch until the PR is in lnd master https://github.com/lightningnetwork/lnd/pull/3282

**Comment by otech47** [comment]
Was able to build successfully and made a new PR: https://github.com/lightninglabs/lightning-app/pull/1275

If you'd rather I rebase and force push to this same branch I can do that too

**Pull request closed without merging**
