### PR TITLE
Add support for Windows lightning links

### PR DESCRIPTION
**Pull request by erkarl**
In this PR we:
* Restrict the application to run in a single instance mode. If the user tries to run the second instance we close the 2nd instance and focus the running application.
* Add additional logic to catch the protocol (`lightning:invoice`) links on Windows since it doesn't trigger the `open-url` callback.

Closes: https://github.com/lightninglabs/lightning-app/issues/665

### CODE REVIEW

**Comment by tanx** [comment]
@erkarl nice. @valentinewallace were you able to confirm this on your windows machine?

**Comment by molxyz** [comment]
Tested on Windows 10 on browsers Chrome, Firefox, and Microsoft Edge. No second app opens when making payment by using `lightning:invoice`; however, it does open a blank browser screen with a popup asking if user wants to open Lightning app. Can we have this popup to stay on the same webpage?  Something like this screenshot of Bitrefill payment page: 

image

**Comment by erkarl** [comment]
@molxyz just to confirm - you tested it with the current release? Did it automatically fill in the invoice information as well?

**Comment by molxyz** [comment]
@erkarl 
>just to confirm - you tested it with the current release? Did it automatically fill in the invoice information as well?
Yes I think so. I started out by cloning the lightning-app repo, tested by running it first to make sure it worked so it should be the current release?  Here are the last lines of this build when I ran `npm run electron-pack`: 
```
> lightning-app@0.2.6-alpha electron-pack C:\Users\moli\APP-BUILD\lightning-app
> build --c.extraMetadata.main=build/electron.js

  • electron-builder version=20.14.7
  • loaded configuration file=package.json ("build" field)
  • loaded parent configuration preset=react-cra
  • writing effective config file=dist\electron-builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=3.0.3 appOutDir=dist\win-unpacked
  • downloading               path=C:\Users\moli\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-2.0.0 url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.0.0/winCodeSign-2.0.0.7z
  • building        target=nsis file=dist\Lightning-win32v0.2.6-alpha.exe archs=x64 oneClick=true
  • downloading               path=C:\Users\moli\AppData\Local\electron-builder\cache\nsis\nsis-3.0.3.0 url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.3.0/nsis-3.0.3.0.7z
  • downloading               path=C:\Users\moli\AppData\Local\electron-builder\cache\nsis\nsis-resources-3.3.0 url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.3.0/nsis-resources-3.3.0.7z
  • building block map blockMapFile=dist\Lightning-win32v0.2.6-alpha.exe.blockmap
```
But when I compiled your PR, not sure why `npm run electron-pack` gives a different version. Here are the few last lines: 
```
> lightning-app@0.2.1-alpha electron-pack C:\Users\moli\APP-BUILD\lightning-app
> build --c.extraMetadata.main=build/electron.js

  • electron-builder version=20.14.7
  • loaded configuration file=package.json ("build" field)
  • loaded parent configuration preset=react-cra
  • writing effective config file=dist\electron-builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=1.8.7 appOutDir=dist\win-unpacked
Downloading tmp-34532-1-SHASUMS256.txt-1.8.7
[============================================>] 100.0% of 5.74 kB (5.74 kB/s)
  • building        target=nsis file=dist\Lightning-win32v0.2.1-alpha.exe archs=x64 oneClick=true
  • building block map blockMapFile=dist\Lightning-win32v0.2.1-alpha.exe.blockmap
```

**Comment by valentinewallace** [comment]
Finally got the windows build working thanks to @molxyz :) This works for me! I don't get a popup on the same page, instead in a separate small window, which I think is acceptable.

I'm in favor of merging this for now and possibly opening a separate issue for the blank tab problem.

capture

**Pull request merged**
